.drone.yml
=> chore: better build cache

adm/conf_monitor.sh
=> fix: don't start plugins during installation or uninstallation

plugins/switch/config.ini, plugins/switch/main.py
=> fix: fix missing configuration for no_match policy in switch plugin

layers/layer1_python3/0200_xattrfile/tests/test_basic.py, layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
and destination are not in the same FS
Close: #29
=> fix: fix issues with xattrfile move_or_copy/hardlink_or_copy 

plugins/switch/main.py
=> fix: fix magic identification at plugin level override

config/circus.ini.custom
About metwork-framework/mfcom#82
=> [WIP] build: change for new mfcom autorestart plugin

layers/layer1_python3/0200_xattrfile/tests/test_basic.py, layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
mfdata plugins
The test test_14_move_or_copy2 is broken, we temporarily skip it
close #53
=> fix: Fix loss of files between plugin switch and plugin ungzip or other

integration_tests/0002_switch_ungzip_archive_plugins/test.sh
=> fix: fix intermittent fails of mfdata integration tests

doc/Makefile
=> docs: we prefer to keep a specific list of what we copy to doc

config/crontab.custom
=> fix: add garbage_collector.sh call in crontab

config/circus.ini.custom, config/config.ini, config/nginx.conf
=> feat: introduce log management with mfadmin

adm/_make_circus_conf, adm/templates/plugins/archive/{{cookiecutter.name}}/config.ini, adm/templates/plugins/default/{{cookiecutter.name}}/config.ini, adm/templates/plugins/delete/{{cookiecutter.name}}/config.ini, adm/templates/plugins/fork/{{cookiecutter.name}}/config.ini, adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini, adm/templates/plugins/move/{{cookiecutter.name}}/config.ini
=> feat: port "extra_daemon" feature from mfserv to mfdata

bootstrap.sh, doc/mfdata_load_env.md, doc/mfdata_miscellaneous.md, doc/mfdata_quick_start.md, layers/layer1_python3/layer_custom.md
- fix building issues with proxy : add export 'proxy' variable in bootstrap.sh
- fix typo in documentation
=> fix: fix building issues with proxy

plugins/switch/main.py
=> fix: fix issue 'bad magic file in a plugin can break the switch plugin'

doc/Makefile, doc/mfdata_miscellaneous.md, doc/mfdata_tuning_monitoring.md
- Update MFDATA documentation
- fix typo
- fix bug CHANGELOGS not generated when CHANGELOGS.md doesn't exist (for the first time)
=> docs: Update MFDATA documentation

plugins/mqtt_listener/bin/extra_daemon_mqtt_listener.py
Thanks to @dearith
Close: #166
=> fix: fix logging issue with mqtt_listener in some cases

layers/layer1_python3/0200_xattrfile/tests/test_basic.py, layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py, plugins/switch/main.py
=> fix: fix some warnings on switch plugin with hardlinking

adm/templates/plugins/_common/config.ini, adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini
from 100MB to 10GB
Close: #184
=> feat: increase default file size limit for plugins

config/content_by_lua.lua
for directory name and file name
=> feat: allow "-" and "." in http receiver

layers/layer1_python3/0200_xattrfile/tests/test_basic.py, layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py, plugins/switch/main.py
=> feat: change the behavior of hardlinks methods to provide atomicity

layers/layer1_python3/0300_acquisition/acquisition/step.py
=> fix: fix failure_policy_move_keep_tags configuration key

layers/layer1_python3/0300_acquisition/acquisition/step.py
=> fix: fix get_original_basename/dirname behaviour in debug mode

adm/_make_circus_conf, adm/_make_directory_observer_conf, adm/_make_switch_conf, adm/before_start_directory_observer, layers/layer1_python3/0100_directory_observer/directory_observer/directory_observer.py, layers/layer1_python3/0100_directory_observer/requirements.txt, plugins/switch/main.py
See metwork-framework/resources#52
=> build: configparser_extended drop

plugins/switch/main.py
=> feat: improve debug logs for switch plugin

config/content_by_lua.lua
=> feat: allow empty nginx uploads

plugins/switch/main.py
=> build: revert new eval behaviour with a feature flag

layers/layer1_python3/0300_acquisition/acquisition/base.py, layers/layer1_python3/0300_acquisition/acquisition/copy_step.py, layers/layer1_python3/0300_acquisition/acquisition/move_step.py, layers/layer1_python3/0300_acquisition/acquisition/reinject_step.py, layers/layer1_python3/0300_acquisition/acquisition/step.py, layers/layer1_python3/0300_acquisition/acquisition/switch_rules.py, layers/layer1_python3/0300_acquisition/acquisition/switch_step.py, layers/layer1_python3/0300_acquisition/acquisition/transform_step.py, layers/layer1_python3/0300_acquisition/acquisition/utils.py
=> feat: preparing issue227

docs/950-old_docs/mfdata_and_magic.md
=> docs: Fix Wikipedia link in doc

plugins/amqplistener/bin/amqp_listener.py
=> fix: self._consumer.on_message is not set after exception

adm/templates/plugins/_common/config.ini
See metwork-framework/mfserv#433
=> docs: fix a comment in plugin config.ini

adm/templates/plugins/listener/{{cookiecutter.name}}/.plugin_format_version
=> fix: fix missing file in listener template

adm/_make_circus_conf
See metwork-framework/acquisition#14
=> fix: configure step failure policy for reinject steps

plugins/ftpsend/main.py
=> fix: fix typo in error messsage

plugins/switch/config.ini.custom
=> fix: fix #420 switch_no_match_policy not taken into account

config/config.ini.custom
related to https://github.com/metwork-framework/acquisition/pull/25
=> feat: keep original file name in trash directory
